export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const ERROR_ROUTE = '*'
export const COURSE_ROUTE = '/courses/:slug'
export const PASSWORD_ROUTE = '/forget/password'
export const ADMIN_REGISTRATION_ROUTE = '/admin/registration'
export const ADMIN_COURSES_ROUTE = '/admin/courses'
export const ADMIN_USERS_ROUTE = '/admin/users'
export const ADMIN_FINISHED_ROUTE = '/admin/finished'
export const ADMIN_SUGGESTIONS_ROUTE = '/admin/suggestions'
export const ADMIN_QUESTION_ROUTE = '/admin/question'
export const ADMIN_EDIT_ROUTE = '/admin/edit'
export const ADMIN_CREATE_ROUTE = '/admin/create'
export const ADMIN_POSITIONS_ROUTE = '/admin/positions'
export const ADMIN_CHANGE_USER = '/admin/change/user/:id'
export const ADMIN_CHANGE_COURSE = '/admin/change/course/:id'



export const USER_RULES_ROUTE = '/user/rules'
export const USER_COURSES_ROUTE = '/user/courses'
export const USER_PROGRESS_ROUTE = '/user/progress'
export const USER_FAQ_ROUTE = '/user/faq'
export const USER_PASSWORD_ROUTE = '/user/password'
